include kitty.conf

# Force tab/title bar to always show even with 1 tab
tab_bar_min_tabs            1
tab_bar_edge                top
tab_bar_style               slant
tab_bar_align               center
tab_powerline_style         slanted

# Display the window title (current directory or process)
tab_title_template          " {title} "

