splash = false

wallpaper {
    monitor = desc:Dell Inc. DELL U2724DE 1DMQD34
    path = ~/.local/share/wallpapers/1
    fit_mode = cover
}

wallpaper {
    monitor = desc:Dell Inc. DELL U2724DE 7583G34
    path = ~/.local/share/wallpapers/2
    fit_mode = cover
}
