
[font]
size = 13.0

[font.normal]
family = "FiraCode Nerd Font"

[[keyboard.bindings]]
chars = "\r"
key = "NumpadEnter"

[window]
option_as_alt = "OnlyLeft"

[window.padding]
x = 2
y = 2

[general]
import = ["~/.config/alacritty/themes/tender.toml"]
